Online_job_portal-main/Job_portal/Job_portal/Controllers/CompanyController.cs
using Job_portal.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Job_portal.Controllers
{
    public class CompanyController : Controller
    {
        job_DatabaseEntities1 db = new job_DatabaseEntities1();
        // GET: Company
        public ActionResult Index()
        {
            try
            {
                Response.Cache.SetNoStore();
                TempData["companyname"] = Session["companyname"].ToString();
                //show posted job
                var getpostedjob = db.PostJob_tb.ToList();
                ViewBag.showpostedjob = getpostedjob;

                //count total job seeker
                var countjobseeker = db.jobseeker_tb.Count();
                ViewBag.showcountjobseeker = countjobseeker;

                //count total company
                var countcompany = db.Company_tb.Count();
                ViewBag.showcountcompany = countcompany;

                //count total posted job
                var countpostedjob = db.PostJob_tb.Count();
                ViewBag.showcountpostedjob = countpostedjob;

                //count total apply job
                var countapplyjob = db.ApplyJob_tb.Count();
                ViewBag.showcountapplyjob = countapplyjob;
            }
            catch (Exception ex)
            {
                ViewBag.ss = ex.ToString();
                return RedirectToAction("login","Company");
            }
            return View();
        }


        public ActionResult companyRegistration()
        {
            return View();
        }
        [HttpPost]
        public ActionResult companyRegistration(Company_tb comtb)
        {
            if(ModelState.IsValid)
            {
                db.Entry(comtb).State = EntityState.Added;
                comtb.EntryDate = DateTime.Now;
                comtb.Status = 1;
                db.SaveChanges();
                return RedirectToAction("login");
            }
            return View(comtb);
        }
        public ActionResult login()
        {
            if (Session["comid"] != null)
            {
                return RedirectToAction("Index", "Company");
            }
            return View();
        }
        [HttpPost]
        public ActionResult login(Company_tb comtblogin)
        {
            try
            {
                var a = db.Company_tb.Where(l => l.UserName == comtblogin.UserName && l.Password == comtblogin.Password).SingleOrDefault();
                if (a != null)
                {
                    Session["comid"] = a.CID.ToString();
                    //ViewBag.jstatus = "not applied";
                    Session["companyname"] = a.CNAME.ToString();

                    return RedirectToAction("index","Company");
                }
                else
                {
                    TempData["msg"] = "Invalid User Name or Password";
                    return RedirectToAction("login", "Company");
                }
            }
            catch (Exception ex)
            {
                ViewBag.s = ex.ToString();
                return RedirectToAction("login", "Company");
            }
        }

        public ActionResult AddJobPosting()
        {
            ViewBag.showjobcat = new SelectList(db.job_categorytb, "job_cat_id", "job_cat_name");
            ViewBag.showjoblocation = new SelectList(db.Job_location, "JobLocation_ID", "Location_Name");

            return View();
        }
        [HttpPost]
        public ActionResult AddJobPosting(PostJob_tb pstb, DateTime dates)
        {
            if(ModelState.IsValid)
            {
                db.Entry(pstb).State = EntityState.Added;
                pstb.Company_ID = Convert.ToInt32(Session["comid"]);
                pstb.JobStatus = 0;
                pstb.EntryDate = DateTime.Now;
                pstb.LastApplyDate = dates;
                db.SaveChanges();
                TempData["success"] = "Job Post Successfully Done";
                return RedirectToAction("AddJobPosting");
            }
            return View(pstb);
        }

        public ActionResult ViewJobPosting()
        {
            int CompanyID = Convert.ToInt32(Session["comid"]);
            var ShowPostedJob = db.PostJob_tb.Where(x => x.Company_ID == CompanyID).ToList();
            return View(ShowPostedJob);
        }


      
        public ActionResult CheckJobSeeker()
        {
            int idd = Convert.ToInt32(Session["comid"]);
            var p = db.ApplyJob_tb.Where(U => U.Company_ID == idd).ToList();
            ViewBag.p = p;
            return View();
        }
        public ActionResult CheckJobSeekerdata(int id)
        {
            var p = db.jobseeker_tb.Where(U => U.JS_ID == id).ToList();
            var i = db.Education_tb.Where(U => U.Job_seeker_ID == id).ToList();
            ViewBag.i = i;
            ViewBag.p = p;
            
            return View();
        }

        public ActionResult CompanyInfo()
        {
            int CompanyID = Convert.ToInt32(Session["comid"]);
            var checkcompany_info = db.Company_tb.Where(x => x.CID == CompanyID).ToList();
            return View(checkcompany_info);
        }

        public ActionResult companyfullDetailDetail(int id)
        {
            var companyDetails = db.Company_tb.Find(id);
            return View(companyDetails);
        }



        // GET: Company/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Company/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Company/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Company/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Company/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //logout
        public ActionResult logout()
        {
            Session.Abandon();
            Session.Remove("comid");
            Session.RemoveAll();

            return RedirectToAction("login","Company");
        }
    }
}

Online_job_portal-main/Job_portal/Job_portal/Controllers/JobSeekerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_portal.Models;

namespace Job_portal.Controllers
{
    public class JobSeekerController : Controller
    {
        job_DatabaseEntities1 db = new job_DatabaseEntities1();

        // GET: JobSeeker
        public ActionResult Index()
        {
            try
            {
                Response.Cache.SetNoStore();
                TempData["jobseekername"] = Session["jobseekerusername"].ToString();
            }
            catch (Exception ex)
            {
                ViewBag.ss = ex.ToString();
                return RedirectToAction("login", "Home");
            }

            return View();
        }

        public ActionResult JobSeeker()
        {
            int jid = Convert.ToInt32(Session["jsid"]);
            var listjobs = db.jobseeker_tb.Where(x => x.JS_ID == jid).ToList();
            return View(listjobs);
        }

        public ActionResult jobseekerDetail(int id)
        {
            var getjobseeker = db.jobseeker_tb.Find(id);
            return View(getjobseeker);
        }

        public ActionResult EducAtionInfo()
        {
            int jid = Convert.ToInt32(Session["jsid"]);
            var listeducation = db.Education_tb.Where(x => x.Job_seeker_ID== jid).ToList();
            ViewBag.me = listeducation;
            return View(listeducation);
        }

        //Education Detail in popup
        public ActionResult EducationDetail(int id)
        {
            var geteduction = db.Education_tb.Find(id);
            return View(geteduction);
        }

        public ActionResult ApplyJobStatus()
        {
            int jid = Convert.ToInt32(Session["jsid"]);
            var listapplyjob = db.ApplyJob_tb.Where(x => x.Job_seekerID == jid).ToList();
            
            ViewBag.p = listapplyjob;
            return View();


        }

        public ActionResult DownloadResume(int id)
        {

            var a = db.Education_tb.Where(x => x.Job_seeker_ID == id).ToList();
            //var getdetails = db.Education_tb.Find(id);
            ViewBag.p = a;
            return View();
        }


       

        public ActionResult AddNewEducation()
        {
            return View();
        }
        
        public ActionResult SetAddNewEducation(Education_tb jstb, HttpPostedFileBase file)
        {

            if (file != null)
            {
                int jid = Convert.ToInt32(Session["jsid"]);
                String FileExt = System.IO.Path.GetExtension(file.FileName).ToUpper();
                if (FileExt == ".PDF")
                {
                    int randomNumber = new Random().Next(1, 910);
                    var newname = randomNumber + "cv" + jid +FileExt;
                    string docname = System.IO.Path.GetFileName(file.FileName);
                    string savedoc = Server.MapPath("~/jobseekerimages/" + newname);
                    file.SaveAs(savedoc);

                    if (ModelState.IsValid)
                    {
                        db.Entry(jstb).State = System.Data.Entity.EntityState.Added;
                        
                        jstb.Resume = newname;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                else if (FileExt == ".DOCX")
                {
                    int randomNumber = new Random().Next(1, 910);
                    var newname = randomNumber + "cv" + jid + FileExt;
                    string docname = System.IO.Path.GetFileName(file.FileName);
                    string savedoc = Server.MapPath("~/jobseekerimages/" + newname);
                    file.SaveAs(savedoc);

                    if (ModelState.IsValid)
                    {
                        db.Entry(jstb).State = System.Data.Entity.EntityState.Added;

                        jstb.Resume = newname;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                else {
                    ViewBag.o = 1;
                    return View();
                }
            }
            return View(jstb);
        }



        //testing 021


    }
}

Online_job_portal-main/Job_portal/Job_portal/Views/Company/AddJobPosting.cshtml
@model Job_portal.Models.PostJob_tb

@{
    ViewBag.Title = "AddJobPosting";
    Layout = "~/Views/Shared/_LayoutCompanyDashboardDesign.cshtml";
}

<div class="container">
    <h2>Add New Job</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
           
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
               <label class="control-label col-md-2">Company ID</label>
                <div class="col-md-10">
                    @*@Html.DropDownList("Company_ID", null, htmlAttributes: new { @class = "form-control" })*@
                    <input type="text" value="@Session["comid"]" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Company_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Job Category</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.job_cat_id, (SelectList)ViewBag.showjobcat, "Select Job Category", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.job_cat_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Required Skill</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RequiredSkill, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RequiredSkill, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Job Role</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Quolification</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Min_Qualification, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Min_Qualification, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Extra Skill</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ExtraSkill, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExtraSkill, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Max Age</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Max_age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Max_age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Salary</label>
               
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Expected_salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Expected_salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Job Location</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.Job_location, (SelectList)ViewBag.showjoblocation, "Select Location", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Job_location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Working Hour</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Working_Hour, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Working_Hour, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Job Description</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Job_Desc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Job_Desc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Last Apply Date</label>
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.LastApplyDate, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="date" name="dates" class="form-control" />
                    @Html.ValidationMessageFor(model => model.LastApplyDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Contact Person</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact_person, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Contact_person, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Company Name</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Post Job" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <h1 style="color:red">@TempData["success"]</h1>
</div>

Online_job_portal-main/Job_portal/Job_portal/Views/Company/CheckJobSeeker.cshtml
@model IEnumerable<Job_portal.Models.ApplyJob_tb>
@{
    ViewBag.Title = "CheckJobSeeker";
    Layout = "~/Views/Shared/_LayoutCompanyDashboardDesign.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">View Posted Job Details</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="white_box_tittle list_header">

                                <div class="box_right d-flex lms_block">
                                    <div class="serach_field_2">
                                        <div class="search_inner">
                                            <form Active="#">
                                                <div class="search_field">
                                                    <input type="text" placeholder="Search content here...">
                                                </div>
                                                <button type="submit"> <i class="ti-search"></i> </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="add_button ml-10">
                                        <a href="#" data-toggle="modal" data-target="#addcategory" class="btn_1">Add New</a>
                                    </div>
                                </div>
                            </div>

                            <div class="QA_table mb_30">
                                <!-- table-responsive -->
                                <table class="table table-responsive" id="showtable">
                                    <thead>
                                        <tr>
                                            <th scope="col">Job ID</th>
                                            <th scope="col">Company ID</th>
                                            <th scope="col">Job Seeker ID</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Entry Date</th>
                                            

                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.JobID)
                                                </td>

                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Company_ID)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Job_seekerID)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Status)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.EntryDate)
                                                </td>

                                                
                                            </tr>
}


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Online_job_portal-main/Job_portal/Job_portal/Views/Company/ViewJobPosting.cshtml
@model IEnumerable<Job_portal.Models.PostJob_tb>

@{
    ViewBag.Title = "ViewJobPosting";
    Layout = "~/Views/Shared/_LayoutCompanyDashboardDesign.cshtml";
}

<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">View Posted Job Details</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="white_box_tittle list_header">

                                <div class="box_right d-flex lms_block">
                                    <div class="serach_field_2">
                                        <div class="search_inner">
                                            <form Active="#">
                                                <div class="search_field">
                                                    <input type="text" placeholder="Search content here...">
                                                </div>
                                                <button type="submit"> <i class="ti-search"></i> </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="add_button ml-10">
                                        <a href="#" data-toggle="modal" data-target="#addcategory" class="btn_1">Add New</a>
                                    </div>
                                </div>
                            </div>

                            <div class="QA_table mb_30">
                                <!-- table-responsive -->
                                <table class="table table-responsive" id="showtable">
                                    <thead>
                                        <tr>
                                            <th scope="col">Company Name</th>
                                            <th scope="col">Role</th>
                                            <th scope="col">Min Qualification</th>
                                            <th scope="col">Expected Salary</th>
                                            <th scope="col">Job Description</th>
                                            <th scope="col">Action</th>

                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CompanyName)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Role)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Min_Qualification)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Expected_salary)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Job_Desc)
                                </td>

                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Company_ID }, new { @class = "btn btn-primary  btn-sm" })
                                    @*@Html.ActionLink("Details", "Details", new { id = item.JS_ID }, new { @class = "deleteLink btn btn-info btn-sm" })*@
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Company_ID }, new { @class = "btn btn-danger btn-sm" })
                                    <button type="button" class="btn btn-info btn-sm" onclick="Details(@item.Company_ID)" @*data-toggle="modal" data-target="#myModal"*@>Details..</button>
                                </td>
                            </tr>}


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p id="txtfname">

                </p>
                <p>

                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>


<script>
    function Details(id) {
        $.get("@Url.Action("jobseekerDetail", "JobSeeker")/"+id, function (data) { $('.modal-body').html(data); });
        $('#myModal').modal('show');
    }

    $('#myModal').on('hidden.bs.modal' , function (e) {
        $('.modal-body').html("");
    })
</script>

<!-- Trigger the modal with a button -->
<!-- Modal -->




@{
                <script>$(document).ready(function () {
            $("#dialog-confirm").dialog({
                autoOpen: false,
                modal: true,
                resizable: false,
                height: 180,
            });
            $(".deleteLink").click(function (e) {
                e.preventDefault();
                var targetUrl = $(this).attr("href");

                $("#dialog-confirm").dialog({
                    buttons: {
                        "Confirm": function () {
                            window.location.href = targetUrl;
                        },
                        "Cancel": function () {
                            $(this).dialog("close");
                        }
                    }
                });
                $("#dialog-confirm").dialog("open");
            });
        });</script> }

Online_job_portal-main/Job_portal/Job_portal/Views/Company/login.cshtml
@model Job_portal.Models.Company_tb

@{
    ViewBag.Title = "login";
    Layout = "~/Views/Shared/_LayoutFrontDesignBlank.cshtml";
}


<div class="container">
    <br />
    <br />
    <h2>Company Login</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-danger" />
                    <br />
                    <br />
                    <a href="@Url.Action("companyRegistration")">Create New Account</a>
                </div>
            </div>
            
        </div>
        <h4>
            @TempData["msg"]
        </h4>
    }


</div>